"""MCP 工具注册表。"""

from tools import project
from tools import query
from tools import cad
from tools import mesh
from tools import generation
from tools import boundary
from tools import quality
from tools import advanced

TOOLS = (
    project.OpenSpdFile,
    project.SaveSpdFile,
    project.SaveToAnotherSpdFile,
    project.ImportCADFile,
    project.ImportGridFile,
    project.ExportGrid,
    project.ClearData,
    project.ClearGridData,
    query.GetStartAndEndPointByConnector,
    query.GetCurrentSelectedIDs,
    query.GetAllObjectByType,
    cad.UGCADSurfaceTranslate,
    cad.UGCADSurfaceRotate,
    cad.UGCADSurfaceScale,
    cad.UGCADSurfaceMirror,
    cad.UGSurfaceProcessing,
    cad.UGDamageRepari,
    mesh.DeleteConnector,
    mesh.DeleteDomain,
    mesh.DeleteBlock,
    cad.DeleteFC,
    cad.DeleteNbsFace,
    cad.UGSpitAssemblyCreateNewGroup,
    cad.UGSpitAssemblyMoveNodesToNewGroup,
    cad.UGSpitAssemblyRenameGroup,
    cad.UGSpitAssemblyDeleteGroup,
    boundary.BorderConditionAddGroup,
    boundary.BorderConditionDeleteGroup,
    boundary.BorderConditioConfigProperty,
    boundary.BorderConditionSaveDataToDomain,
    quality.ExamineConnector,
    mesh.TranslateMesh,
    cad.TranslateSurface,
    mesh.UGZoomMesh,
    mesh.UGMirrorSur,
    mesh.UGRotateSurf,
    mesh.UGJoinConnector,
    mesh.UGJoinDomain,
    mesh.UGHalfModelLine,
    quality.ExamineBlock,
    quality.ExamineDomain,
    query.GetScreenNormal,
    mesh.MoveEndPoint,
    cad.UGDelRedundantDom,
    cad.UGRepairRedundantDom,
    cad.CADIntersect,
    cad.UGDeleteSubassembly,
    mesh.AssembleDomain,
    mesh.UGAssembleDomain,
    mesh.UGInitialDomain,
    mesh.UGReDimensionSetSpecifiedValue,
    mesh.UGReDimensionCopy,
    mesh.UGReDimensionMatch,
    mesh.UGReDimensionAverageDistribution,
    mesh.UGReDimensionInversionDistribution,
    mesh.UGReDimensionConfigDistribution,
    mesh.UGReDimensionSmoothDistribution,
    generation.UGSur,
    mesh.UGSplitConnector,
    cad.CreateCoons,
    generation.UGBlockCreate,
    generation.UGUGSp,
    mesh.TranslateConnector,
    mesh.CreateConnector,
    project.Undo,
    project.Redo,
    cad.ManualExtractConnector,
    cad.AutoExtractConnector,
    project.ExportCADFile,
    project.ExportSolver_CFX,
    project.ExportSolver_FTS,
    project.ExportSolver,
    mesh.TSplitConnector,
    cad.CADSurfaceScale,
    cad.CADSurfaceRotate,
    cad.CADSurfaceMirror,
    mesh.SplitBlock,
    cad.DealWatertight,
    query.GetModelParameters,
    query.GetDealWatertightTolenrance,
    query.GetAllSpitAssemblyGroupProperty,
    generation.GenerateSurMeshBySpitAssemblyGroupProperty,
    query.GetGenerateSurMeshDefaultParam,
    query.GetCreateBlockDefaultParam,
    # advanced.SegmentPart,
    advanced.SegmentPartDirect,
    advanced.ClassifyTrailingEdgeDomains,
    advanced.DetermineDirectionForType1,
    advanced.IdentifyType2Roles,
    mesh.SetConnectorPointCount,
    mesh.CopyConnectorPointCount,
    mesh.SetConnectorAverageDistribution,
    mesh.SetConnectorSmoothDistribution,
    mesh.SetConnectorConfigDistribution,
    mesh.AssembleConnectorsToDomain,
    query.GetSpliteAssemlyDomains,
    query.GetConnectorsByDomain,
    mesh.MergeEdgesByDomain,
    generation.GenerateLongAndNarrowFaceGrid,
    generation.GenerateANisoDomainGrid,
    query.GetConnectorStartAndEndUnitLenth,
    query.GetPointCount,
    query.GetNewConnectorId,
    query.GetDomainsByType,
)

def register_tools(mcp):
    """按历史顺序注册全部 GridStar 工具。"""
    for tool in TOOLS:
        mcp.tool()(tool)
    return mcp
